# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeamsCli < Formula
  desc "Microsoft Teams CLI"
  homepage "https://github.com/truls27a/teams-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/truls27a/teams-cli/releases/download/v0.2.0/teams-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "a7773a8f0c2c02efa8ff079e0375dfdd11bc8ee7ffd1b0140661a1190ecc27b7"

      define_method(:install) do
        bin.install "teams"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/truls27a/teams-cli/releases/download/v0.2.0/teams-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "88790fbf88f6c9f977129fd2afbdd94fd2713a4a7cbc86caff1b1852e1381019"

      define_method(:install) do
        bin.install "teams"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/truls27a/teams-cli/releases/download/v0.2.0/teams-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "c590b038deb978f9643c7e2d9038faf82f48734244f6db0f50ea3f6ac6e7352d"
      define_method(:install) do
        bin.install "teams"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/truls27a/teams-cli/releases/download/v0.2.0/teams-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "b444cbf42770a3fec4b7d6ed4d9fc82614460ca3b0a55a43e3c3e58076569181"
      define_method(:install) do
        bin.install "teams"
      end
    end
  end

  service do
    run [opt_bin/"teams", "watch"]
    keep_alive true
    log_path var/"log/teams-cli.log"
    error_log_path var/"log/teams-cli.log"
  end

  test do
    system "#{bin}/teams", "--help"
  end
end
