# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeamsCli < Formula
  desc "Microsoft Teams CLI"
  homepage "https://github.com/truls27a/teams-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/truls27a/teams-cli/releases/download/v0.3.0/teams-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "133face87d655a8c0a9a8cb37edcda7847992035bce2ab90f8bab72cc9fa10e7"

      define_method(:install) do
        bin.install "teams"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/truls27a/teams-cli/releases/download/v0.3.0/teams-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "ee51229fc7513ff2fbcdfd7c75750c3559268cb59be2e95fe32dc82cf635db23"

      define_method(:install) do
        bin.install "teams"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/truls27a/teams-cli/releases/download/v0.3.0/teams-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "34eab168f5355891a82db75a8f8fdffff5d9d9e84986d776dbaeae2ca8d3a0b9"
      define_method(:install) do
        bin.install "teams"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/truls27a/teams-cli/releases/download/v0.3.0/teams-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "0b3c24beebdbbf6a227c32f23013e00a20c1d18e29adc6c1ba81b3604532f195"
      define_method(:install) do
        bin.install "teams"
      end
    end
  end

  service do
    run [opt_bin/"teams", "watch"]
    keep_alive true
    log_path var/"log/teams-cli.log"
    error_log_path var/"log/teams-cli.log"
  end

  test do
    system "#{bin}/teams", "--help"
  end
end
