# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeamsCli < Formula
  desc "Microsoft Teams CLI"
  homepage "https://github.com/truls27a/teams-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/truls27a/teams-cli/releases/download/v0.1.0/teams-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "b294be8b5625c5eb74280bc6ffbd602dde2e04cebcda26803013080ee76229ae"

      define_method(:install) do
        bin.install "teams"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/truls27a/teams-cli/releases/download/v0.1.0/teams-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "d2ab2edcea6a6f4bfea657d3c17e1abc4397fa51df661e28ec7ab3337a06fa48"

      define_method(:install) do
        bin.install "teams"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/truls27a/teams-cli/releases/download/v0.1.0/teams-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "5243e73e1da649b480962af6a3efca921d947536baae341c4f29d5bfab8ddd63"
      define_method(:install) do
        bin.install "teams"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/truls27a/teams-cli/releases/download/v0.1.0/teams-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "ad6a165353b327086b24d0482fceab48bd0b2319e64b7cb7bbf8bc0776d359d2"
      define_method(:install) do
        bin.install "teams"
      end
    end
  end

  test do
    system "#{bin}/teams", "--help"
  end
end
